#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skywolf.DatabaseRepository
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MarketData")]
	public partial class MarketDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVA_APIKeyList(VA_APIKeyList instance);
    partial void UpdateVA_APIKeyList(VA_APIKeyList instance);
    partial void DeleteVA_APIKeyList(VA_APIKeyList instance);
    partial void InsertVA_Prices_D1(VA_Prices_D1 instance);
    partial void UpdateVA_Prices_D1(VA_Prices_D1 instance);
    partial void DeleteVA_Prices_D1(VA_Prices_D1 instance);
    partial void InsertVA_Prices_H1(VA_Prices_H1 instance);
    partial void UpdateVA_Prices_H1(VA_Prices_H1 instance);
    partial void DeleteVA_Prices_H1(VA_Prices_H1 instance);
    partial void InsertVA_Prices_M1(VA_Prices_M1 instance);
    partial void UpdateVA_Prices_M1(VA_Prices_M1 instance);
    partial void DeleteVA_Prices_M1(VA_Prices_M1 instance);
    partial void InsertVA_Prices_M15(VA_Prices_M15 instance);
    partial void UpdateVA_Prices_M15(VA_Prices_M15 instance);
    partial void DeleteVA_Prices_M15(VA_Prices_M15 instance);
    partial void InsertVA_Prices_M30(VA_Prices_M30 instance);
    partial void UpdateVA_Prices_M30(VA_Prices_M30 instance);
    partial void DeleteVA_Prices_M30(VA_Prices_M30 instance);
    partial void InsertVA_Prices_M5(VA_Prices_M5 instance);
    partial void UpdateVA_Prices_M5(VA_Prices_M5 instance);
    partial void DeleteVA_Prices_M5(VA_Prices_M5 instance);
    partial void InsertVA_Prices_MN(VA_Prices_MN instance);
    partial void UpdateVA_Prices_MN(VA_Prices_MN instance);
    partial void DeleteVA_Prices_MN(VA_Prices_MN instance);
    partial void InsertVA_Prices_W1(VA_Prices_W1 instance);
    partial void UpdateVA_Prices_W1(VA_Prices_W1 instance);
    partial void DeleteVA_Prices_W1(VA_Prices_W1 instance);
    partial void InsertVA_AdjPrices_D1(VA_AdjPrices_D1 instance);
    partial void UpdateVA_AdjPrices_D1(VA_AdjPrices_D1 instance);
    partial void DeleteVA_AdjPrices_D1(VA_AdjPrices_D1 instance);
    partial void InsertVA_AdjPrices_MN(VA_AdjPrices_MN instance);
    partial void UpdateVA_AdjPrices_MN(VA_AdjPrices_MN instance);
    partial void DeleteVA_AdjPrices_MN(VA_AdjPrices_MN instance);
    partial void InsertVA_AdjPrices_W1(VA_AdjPrices_W1 instance);
    partial void UpdateVA_AdjPrices_W1(VA_AdjPrices_W1 instance);
    partial void DeleteVA_AdjPrices_W1(VA_AdjPrices_W1 instance);
    #endregion
		
		public MarketDataDataContext() : 
				base(global::Skywolf.DatabaseRepository.Properties.Settings.Default.MarketDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MarketDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MarketDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VA_APIKeyList> VA_APIKeyLists
		{
			get
			{
				return this.GetTable<VA_APIKeyList>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_D1> VA_Prices_D1s
		{
			get
			{
				return this.GetTable<VA_Prices_D1>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_H1> VA_Prices_H1s
		{
			get
			{
				return this.GetTable<VA_Prices_H1>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_M1> VA_Prices_M1s
		{
			get
			{
				return this.GetTable<VA_Prices_M1>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_M15> VA_Prices_M15s
		{
			get
			{
				return this.GetTable<VA_Prices_M15>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_M30> VA_Prices_M30s
		{
			get
			{
				return this.GetTable<VA_Prices_M30>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_M5> VA_Prices_M5s
		{
			get
			{
				return this.GetTable<VA_Prices_M5>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_MN> VA_Prices_MNs
		{
			get
			{
				return this.GetTable<VA_Prices_MN>();
			}
		}
		
		public System.Data.Linq.Table<VA_Prices_W1> VA_Prices_W1s
		{
			get
			{
				return this.GetTable<VA_Prices_W1>();
			}
		}
		
		public System.Data.Linq.Table<VA_AdjPrices_D1> VA_AdjPrices_D1s
		{
			get
			{
				return this.GetTable<VA_AdjPrices_D1>();
			}
		}
		
		public System.Data.Linq.Table<VA_AdjPrices_MN> VA_AdjPrices_MNs
		{
			get
			{
				return this.GetTable<VA_AdjPrices_MN>();
			}
		}
		
		public System.Data.Linq.Table<VA_AdjPrices_W1> VA_AdjPrices_W1s
		{
			get
			{
				return this.GetTable<VA_AdjPrices_W1>();
			}
		}
		
		public System.Data.Linq.Table<vw_InstrumentName> vw_InstrumentNames
		{
			get
			{
				return this.GetTable<vw_InstrumentName>();
			}
		}
		
		public System.Data.Linq.Table<vw_PricingRule> vw_PricingRules
		{
			get
			{
				return this.GetTable<vw_PricingRule>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.APIKeyList")]
	public partial class VA_APIKeyList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.DateTime _EnterTime;
		
		private System.Nullable<System.DateTime> _ExpireTime;
		
		private string _Key;
		
		private bool _Active;
		
		private string _Usr;
		
		private System.Nullable<System.DateTime> _TS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnEnterTimeChanging(System.DateTime value);
    partial void OnEnterTimeChanged();
    partial void OnExpireTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnExpireTimeChanged();
    partial void OnKeyChanging(string value);
    partial void OnKeyChanged();
    partial void OnActiveChanging(bool value);
    partial void OnActiveChanged();
    partial void OnUsrChanging(string value);
    partial void OnUsrChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    #endregion
		
		public VA_APIKeyList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterTime", DbType="DateTime NOT NULL")]
		public System.DateTime EnterTime
		{
			get
			{
				return this._EnterTime;
			}
			set
			{
				if ((this._EnterTime != value))
				{
					this.OnEnterTimeChanging(value);
					this.SendPropertyChanging();
					this._EnterTime = value;
					this.SendPropertyChanged("EnterTime");
					this.OnEnterTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpireTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpireTime
		{
			get
			{
				return this._ExpireTime;
			}
			set
			{
				if ((this._ExpireTime != value))
				{
					this.OnExpireTimeChanging(value);
					this.SendPropertyChanging();
					this._ExpireTime = value;
					this.SendPropertyChanged("ExpireTime");
					this.OnExpireTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr", DbType="VarChar(200)")]
		public string Usr
		{
			get
			{
				return this._Usr;
			}
			set
			{
				if ((this._Usr != value))
				{
					this.OnUsrChanging(value);
					this.SendPropertyChanging();
					this._Usr = value;
					this.SendPropertyChanged("Usr");
					this.OnUsrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_D1")]
	public partial class VA_Prices_D1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_D1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_H1")]
	public partial class VA_Prices_H1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_H1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_M1")]
	public partial class VA_Prices_M1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_M1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_M15")]
	public partial class VA_Prices_M15 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_M15()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_M30")]
	public partial class VA_Prices_M30 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_M30()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_M5")]
	public partial class VA_Prices_M5 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_M5()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_MN")]
	public partial class VA_Prices_MN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_MN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.Prices_W1")]
	public partial class VA_Prices_W1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<System.DateTime> _TS;
		
		private System.Nullable<decimal> _MarketCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    partial void OnMarketCapChanging(System.Nullable<decimal> value);
    partial void OnMarketCapChanged();
    #endregion
		
		public VA_Prices_W1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarketCap", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> MarketCap
		{
			get
			{
				return this._MarketCap;
			}
			set
			{
				if ((this._MarketCap != value))
				{
					this.OnMarketCapChanging(value);
					this.SendPropertyChanging();
					this._MarketCap = value;
					this.SendPropertyChanged("MarketCap");
					this.OnMarketCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.AdjPrices_D1")]
	public partial class VA_AdjPrices_D1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<double> _AdjClose;
		
		private System.Nullable<double> _DividendAmount;
		
		private System.Nullable<double> _SplitCoefficient;
		
		private System.Nullable<System.DateTime> _TS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnAdjCloseChanging(System.Nullable<double> value);
    partial void OnAdjCloseChanged();
    partial void OnDividendAmountChanging(System.Nullable<double> value);
    partial void OnDividendAmountChanged();
    partial void OnSplitCoefficientChanging(System.Nullable<double> value);
    partial void OnSplitCoefficientChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    #endregion
		
		public VA_AdjPrices_D1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClose", DbType="Float")]
		public System.Nullable<double> AdjClose
		{
			get
			{
				return this._AdjClose;
			}
			set
			{
				if ((this._AdjClose != value))
				{
					this.OnAdjCloseChanging(value);
					this.SendPropertyChanging();
					this._AdjClose = value;
					this.SendPropertyChanged("AdjClose");
					this.OnAdjCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DividendAmount", DbType="Float")]
		public System.Nullable<double> DividendAmount
		{
			get
			{
				return this._DividendAmount;
			}
			set
			{
				if ((this._DividendAmount != value))
				{
					this.OnDividendAmountChanging(value);
					this.SendPropertyChanging();
					this._DividendAmount = value;
					this.SendPropertyChanged("DividendAmount");
					this.OnDividendAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplitCoefficient", DbType="Float")]
		public System.Nullable<double> SplitCoefficient
		{
			get
			{
				return this._SplitCoefficient;
			}
			set
			{
				if ((this._SplitCoefficient != value))
				{
					this.OnSplitCoefficientChanging(value);
					this.SendPropertyChanging();
					this._SplitCoefficient = value;
					this.SendPropertyChanged("SplitCoefficient");
					this.OnSplitCoefficientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.AdjPrices_MN")]
	public partial class VA_AdjPrices_MN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<double> _AdjClose;
		
		private System.Nullable<double> _DividendAmount;
		
		private System.Nullable<System.DateTime> _TS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnAdjCloseChanging(System.Nullable<double> value);
    partial void OnAdjCloseChanged();
    partial void OnDividendAmountChanging(System.Nullable<double> value);
    partial void OnDividendAmountChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    #endregion
		
		public VA_AdjPrices_MN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClose", DbType="Float")]
		public System.Nullable<double> AdjClose
		{
			get
			{
				return this._AdjClose;
			}
			set
			{
				if ((this._AdjClose != value))
				{
					this.OnAdjCloseChanging(value);
					this.SendPropertyChanging();
					this._AdjClose = value;
					this.SendPropertyChanged("AdjClose");
					this.OnAdjCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DividendAmount", DbType="Float")]
		public System.Nullable<double> DividendAmount
		{
			get
			{
				return this._DividendAmount;
			}
			set
			{
				if ((this._DividendAmount != value))
				{
					this.OnDividendAmountChanging(value);
					this.SendPropertyChanging();
					this._DividendAmount = value;
					this.SendPropertyChanged("DividendAmount");
					this.OnDividendAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="av.AdjPrices_W1")]
	public partial class VA_AdjPrices_W1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<double> _AdjClose;
		
		private System.Nullable<double> _DividendAmount;
		
		private System.Nullable<System.DateTime> _TS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSIDChanging(long value);
    partial void OnSIDChanged();
    partial void OnAsOfDateChanging(System.DateTime value);
    partial void OnAsOfDateChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnAdjCloseChanging(System.Nullable<double> value);
    partial void OnAdjCloseChanged();
    partial void OnDividendAmountChanging(System.Nullable<double> value);
    partial void OnDividendAmountChanged();
    partial void OnTSChanging(System.Nullable<System.DateTime> value);
    partial void OnTSChanged();
    #endregion
		
		public VA_AdjPrices_W1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this.OnSIDChanging(value);
					this.SendPropertyChanging();
					this._SID = value;
					this.SendPropertyChanged("SID");
					this.OnSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this.OnAsOfDateChanging(value);
					this.SendPropertyChanging();
					this._AsOfDate = value;
					this.SendPropertyChanged("AsOfDate");
					this.OnAsOfDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,7)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdjClose", DbType="Float")]
		public System.Nullable<double> AdjClose
		{
			get
			{
				return this._AdjClose;
			}
			set
			{
				if ((this._AdjClose != value))
				{
					this.OnAdjCloseChanging(value);
					this.SendPropertyChanging();
					this._AdjClose = value;
					this.SendPropertyChanged("AdjClose");
					this.OnAdjCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DividendAmount", DbType="Float")]
		public System.Nullable<double> DividendAmount
		{
			get
			{
				return this._DividendAmount;
			}
			set
			{
				if ((this._DividendAmount != value))
				{
					this.OnDividendAmountChanging(value);
					this.SendPropertyChanging();
					this._DividendAmount = value;
					this.SendPropertyChanged("DividendAmount");
					this.OnDividendAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this.OnTSChanging(value);
					this.SendPropertyChanging();
					this._TS = value;
					this.SendPropertyChanged("TS");
					this.OnTSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sec.vw_InstrumentName")]
	public partial class vw_InstrumentName
	{
		
		private long _SID;
		
		private string _Name;
		
		public vw_InstrumentName()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="price.vw_PricingRule")]
	public partial class vw_PricingRule
	{
		
		private long _SID;
		
		private System.DateTime _AsOfDate;
		
		private string _DataSource;
		
		private string _Ticker;
		
		private string _TimeZone;
		
		private bool _Active;
		
		private string _Usr;
		
		private System.Nullable<System.DateTime> _TS;
		
		public vw_PricingRule()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL")]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="Date NOT NULL")]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this._AsOfDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSource", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DataSource
		{
			get
			{
				return this._DataSource;
			}
			set
			{
				if ((this._DataSource != value))
				{
					this._DataSource = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="VarChar(250)")]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this._Ticker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", DbType="VarChar(200)")]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit NOT NULL")]
		public bool Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr", DbType="VarChar(200)")]
		public string Usr
		{
			get
			{
				return this._Usr;
			}
			set
			{
				if ((this._Usr != value))
				{
					this._Usr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this._TS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
