<?xml version="1.0" encoding="utf-8"?><Database Name="MarketData" Class="MarketDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-N2OTR2I1\SKYWOLFDB;Initial Catalog=MarketData;Persist Security Info=True;User ID=liangshu" SettingsObjectName="Skywolf.DatabaseRepository.Properties.Settings" SettingsPropertyName="MarketDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="av.APIKeyList" Member="VA_APIKeyLists">
    <Type Name="VA_APIKeyList">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_D1" Member="VA_Prices_D1s">
    <Type Name="VA_Prices_D1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_H1" Member="VA_Prices_H1s">
    <Type Name="VA_Prices_H1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M1" Member="VA_Prices_M1s">
    <Type Name="VA_Prices_M1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M15" Member="VA_Prices_M15s">
    <Type Name="VA_Prices_M15">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M30" Member="VA_Prices_M30s">
    <Type Name="VA_Prices_M30">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M5" Member="VA_Prices_M5s">
    <Type Name="VA_Prices_M5">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_MN" Member="VA_Prices_MNs">
    <Type Name="VA_Prices_MN">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_W1" Member="VA_Prices_W1s">
    <Type Name="VA_Prices_W1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_D1" Member="VA_AdjPrices_D1s">
    <Type Name="VA_AdjPrices_D1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SplitCoefficient" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_MN" Member="VA_AdjPrices_MNs">
    <Type Name="VA_AdjPrices_MN">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_W1" Member="VA_AdjPrices_W1s">
    <Type Name="VA_AdjPrices_W1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sec.vw_InstrumentName" Member="vw_InstrumentNames">
    <Type Name="vw_InstrumentName">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="price.vw_PricingRule" Member="vw_PricingRules">
    <Type Name="vw_PricingRule">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataSource" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TimeZone" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>