<?xml version="1.0" encoding="utf-8"?><Database Name="MarketData" Class="MarketDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-N2OTR2I1\SKYWOLFDB;Initial Catalog=MarketData;Persist Security Info=True;User ID=liangshu" SettingsObjectName="Skywolf.DatabaseRepository.Properties.Settings" SettingsPropertyName="MarketDataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="av.Prices_D1" Member="VA_Prices_D1s">
    <Type Name="VA_Prices_D1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_H1" Member="VA_Prices_H1s">
    <Type Name="VA_Prices_H1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M1" Member="VA_Prices_M1s">
    <Type Name="VA_Prices_M1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M15" Member="VA_Prices_M15s">
    <Type Name="VA_Prices_M15">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M30" Member="VA_Prices_M30s">
    <Type Name="VA_Prices_M30">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M5" Member="VA_Prices_M5s">
    <Type Name="VA_Prices_M5">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_MN" Member="VA_Prices_MNs">
    <Type Name="VA_Prices_MN">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_W1" Member="VA_Prices_W1s">
    <Type Name="VA_Prices_W1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_D1" Member="VA_AdjPrices_D1s">
    <Type Name="VA_AdjPrices_D1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SplitCoefficient" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_MN" Member="VA_AdjPrices_MNs">
    <Type Name="VA_AdjPrices_MN">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_W1" Member="VA_AdjPrices_W1s">
    <Type Name="VA_AdjPrices_W1">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="sec.vw_InstrumentName" Member="vw_InstrumentNames">
    <Type Name="vw_InstrumentName">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="price.vw_PricingRule" Member="vw_PricingRules">
    <Type Name="vw_PricingRule">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DataSource" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Ticker" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TimeZone" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_D1_Latest" Member="VA_AdjPrices_D1_Latests">
    <Type Name="VA_AdjPrices_D1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SplitCoefficient" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_MN_Latest" Member="VA_AdjPrices_MN_Latests">
    <Type Name="VA_AdjPrices_MN_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.AdjPrices_W1_Latest" Member="VA_AdjPrices_W1_Latests">
    <Type Name="VA_AdjPrices_W1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="AdjClose" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DividendAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_D1_Latest" Member="VA_Prices_D1_Latests">
    <Type Name="VA_Prices_D1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_H1_Latest" Member="VA_Prices_H1_Latests">
    <Type Name="VA_Prices_H1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M1_Latest" Member="VA_Prices_M1_Latests">
    <Type Name="VA_Prices_M1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M15_Latest" Member="VA_Prices_M15_Latests">
    <Type Name="VA_Prices_M15_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M30_Latest" Member="VA_Prices_M30_Latests">
    <Type Name="VA_Prices_M30_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_M5_Latest" Member="VA_Prices_M5_Latests">
    <Type Name="VA_Prices_M5_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_MN_Latest" Member="VA_Prices_MN_Latests">
    <Type Name="VA_Prices_MN_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.Prices_W1_Latest" Member="VA_Prices_W1_Latests">
    <Type Name="VA_Prices_W1_Latest">
      <Column Name="SID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AsOfDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="[Open]" Member="Open" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="High" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Low" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Close]" Member="Close" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MarketCap" Type="System.Decimal" DbType="Decimal(18,7)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="av.APIKeyList" Member="VA_APIKeyLists">
    <Type Name="VA_APIKeyList">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnterTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExpireTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BatchId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="tvc.SymbolList" Member="TVC_SymbolLists">
    <Type Name="TVC_SymbolList">
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="exchange_traded" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="exchange_listed" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="timezone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="minmov" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="minmov2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pricescale" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="pointvalue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="has_intraday" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_no_volume" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="volume_precision" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="tvc_ticker" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="has_daily" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="has_weekly_and_monthly" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="supported_resolutions" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="intraday_multipliers" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="session" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="data_status" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="tvc.Quotes" Member="TVC_Quotes">
    <Type Name="TVC_Quote">
      <Column Name="AsOfDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ch" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="chp" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="short_name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="exchange" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="lp" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ask" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="bid" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="spread" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="open_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="high_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="low_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="prev_close_price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="volume" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Usr" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="tvc.usp_SymbolList_Upsert" Method="usp_SymbolList_Upsert">
    <Parameter Name="name" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="exchange_traded" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="exchange_listed" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="timezone" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="minmov" Type="System.Double" DbType="Float" />
    <Parameter Name="minmov2" Type="System.Double" DbType="Float" />
    <Parameter Name="pricescale" Type="System.Double" DbType="Float" />
    <Parameter Name="pointvalue" Type="System.Double" DbType="Float" />
    <Parameter Name="has_intraday" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="has_no_volume" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="volume_precision" Type="System.Double" DbType="Float" />
    <Parameter Name="tvc_ticker" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="has_daily" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="has_weekly_and_monthly" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="supported_resolutions" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="intraday_multipliers" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="session" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="data_status" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="tvc.usp_Quotes_Upsert" Method="usp_Quotes_Upsert">
    <Parameter Name="asofdate" Type="System.DateTime" DbType="Date" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="ch" Type="System.Double" DbType="Float" />
    <Parameter Name="chp" Type="System.Double" DbType="Float" />
    <Parameter Name="short_name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="exchange" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="description" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="lp" Type="System.Double" DbType="Float" />
    <Parameter Name="ask" Type="System.Double" DbType="Float" />
    <Parameter Name="bid" Type="System.Double" DbType="Float" />
    <Parameter Name="spread" Type="System.Double" DbType="Float" />
    <Parameter Name="open_price" Type="System.Double" DbType="Float" />
    <Parameter Name="high_price" Type="System.Double" DbType="Float" />
    <Parameter Name="low_price" Type="System.Double" DbType="Float" />
    <Parameter Name="prev_close_price" Type="System.Double" DbType="Float" />
    <Parameter Name="volume" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>