#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skywolf.DatabaseRepository
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Trade")]
	public partial class TradeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TradeDataContext() : 
				base(global::Skywolf.DatabaseRepository.Properties.Settings.Default.TradeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TradeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TradeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TradeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TradeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vw_Order> vw_Orders
		{
			get
			{
				return this.GetTable<vw_Order>();
			}
		}
		
		public System.Data.Linq.Table<vw_Trade> vw_Trades
		{
			get
			{
				return this.GetTable<vw_Trade>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Order_Upsert")]
		public int usp_Order_Upsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string account, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> asofdate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orderId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clientId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> permId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SID", DbType="BigInt")] System.Nullable<long> sID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string securityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string securityType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> orderOpenTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string exchange, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string primaryExchange, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string currency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string action, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> totalQuantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string orderType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> limitPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> auxPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string tif, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> activeStartTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> activeStopTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ocaGroup, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ocaType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string orderRef, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> transmit, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parentId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> blockOrder, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> sweepToFill, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> displaySize, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> triggerMethod, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> outsideRth, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> hidden, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> goodAfterTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> goodTillDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> overridePerentageConstraints, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string rule80A, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> allOrNone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> minQty, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string status, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string initMargin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string maintMargin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string equityWithLoan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> commission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> minCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> maxCommission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string commissionCurrency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string warningTaxt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> filled, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> remaining, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> avgFillPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> lastFillPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string whyHeld)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, asofdate, orderId, clientId, permId, sID, securityName, securityType, orderOpenTime, exchange, primaryExchange, currency, action, totalQuantity, orderType, limitPrice, auxPrice, tif, activeStartTime, activeStopTime, ocaGroup, ocaType, orderRef, transmit, parentId, blockOrder, sweepToFill, displaySize, triggerMethod, outsideRth, hidden, goodAfterTime, goodTillDate, overridePerentageConstraints, rule80A, allOrNone, minQty, status, initMargin, maintMargin, equityWithLoan, commission, minCommission, maxCommission, commissionCurrency, warningTaxt, filled, remaining, avgFillPrice, lastFillPrice, whyHeld);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Trade_Upsert")]
		public int usp_Trade_Upsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string account, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> asofdate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> orderId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> clientId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> permId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string execId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SID", DbType="BigInt")] System.Nullable<long> sID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string securityName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string securityType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> tradeTime, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string exchange, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string primaryExchange, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string currency, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string side, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> quantity, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> price, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> liquidation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> cumQty, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> avgPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string orderRef, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string evRule, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> evMultiplier, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string modelCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> commission, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> realizedPNL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> yield, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> yieldRedemptionDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, asofdate, orderId, clientId, permId, execId, sID, securityName, securityType, tradeTime, exchange, primaryExchange, currency, side, quantity, price, liquidation, cumQty, avgPrice, orderRef, evRule, evMultiplier, modelCode, commission, realizedPNL, yield, yieldRedemptionDate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_StrategyFolder_Upsert")]
		public int usp_StrategyFolder_Upsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string account, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> asofdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> permId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SID", DbType="BigInt")] System.Nullable<long> sID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string fund, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string strategy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string folder)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account, asofdate, permId, sID, fund, strategy, folder);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Orders")]
	public partial class vw_Order
	{
		
		private long _RecordID;
		
		private string _UserName;
		
		private string _AccountType;
		
		private string _Account;
		
		private string _Strategy;
		
		private string _Folder;
		
		private System.DateTime _AsOfDate;
		
		private int _OrderId;
		
		private int _ClientId;
		
		private int _PermId;
		
		private long _SID;
		
		private string _SecurityName;
		
		private string _SecurityType;
		
		private System.Nullable<System.DateTime> _OrderOpenTime;
		
		private string _Exchange;
		
		private string _PrimaryExchange;
		
		private string _Currency;
		
		private string _Action;
		
		private double _TotalQuantity;
		
		private string _OrderType;
		
		private System.Nullable<double> _LimitPrice;
		
		private System.Nullable<double> _AuxPrice;
		
		private string _Tif;
		
		private System.Nullable<System.DateTime> _ActiveStartTime;
		
		private System.Nullable<System.DateTime> _ActiveStopTime;
		
		private string _OcaGroup;
		
		private System.Nullable<int> _OcaType;
		
		private string _OrderRef;
		
		private System.Nullable<bool> _Transmit;
		
		private System.Nullable<int> _ParentId;
		
		private System.Nullable<bool> _BlockOrder;
		
		private System.Nullable<bool> _SweepToFill;
		
		private System.Nullable<int> _DisplaySize;
		
		private System.Nullable<int> _TriggerMethod;
		
		private System.Nullable<bool> _OutsideRth;
		
		private System.Nullable<bool> _Hidden;
		
		private System.Nullable<System.DateTime> _GoodAfterTime;
		
		private System.Nullable<System.DateTime> _GoodTillDate;
		
		private System.Nullable<bool> _OverridePerentageConstraints;
		
		private string _Rule80A;
		
		private System.Nullable<bool> _AllOrNone;
		
		private System.Nullable<int> _MinQty;
		
		private string _Status;
		
		private string _InitMargin;
		
		private string _MaintMargin;
		
		private string _EquityWithLoan;
		
		private System.Nullable<double> _Commission;
		
		private System.Nullable<double> _MinCommission;
		
		private System.Nullable<double> _MaxCommission;
		
		private string _CommissionCurrency;
		
		private string _WarningTaxt;
		
		private System.Nullable<double> _Filled;
		
		private System.Nullable<double> _Remaining;
		
		private System.Nullable<double> _AvgFillPrice;
		
		private System.Nullable<double> _LastFillPrice;
		
		private string _WhyHeld;
		
		private string _Usr;
		
		private System.Nullable<System.DateTime> _TS;
		
		public vw_Order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="VarChar(200)")]
		public string AccountType
		{
			get
			{
				return this._AccountType;
			}
			set
			{
				if ((this._AccountType != value))
				{
					this._AccountType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strategy", DbType="VarChar(200)")]
		public string Strategy
		{
			get
			{
				return this._Strategy;
			}
			set
			{
				if ((this._Strategy != value))
				{
					this._Strategy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folder", DbType="VarChar(200)")]
		public string Folder
		{
			get
			{
				return this._Folder;
			}
			set
			{
				if ((this._Folder != value))
				{
					this._Folder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="Date NOT NULL")]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this._AsOfDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this._OrderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="Int NOT NULL")]
		public int ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this._ClientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermId", DbType="Int NOT NULL")]
		public int PermId
		{
			get
			{
				return this._PermId;
			}
			set
			{
				if ((this._PermId != value))
				{
					this._PermId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL")]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityName", DbType="VarChar(200)")]
		public string SecurityName
		{
			get
			{
				return this._SecurityName;
			}
			set
			{
				if ((this._SecurityName != value))
				{
					this._SecurityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityType", DbType="VarChar(200)")]
		public string SecurityType
		{
			get
			{
				return this._SecurityType;
			}
			set
			{
				if ((this._SecurityType != value))
				{
					this._SecurityType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderOpenTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderOpenTime
		{
			get
			{
				return this._OrderOpenTime;
			}
			set
			{
				if ((this._OrderOpenTime != value))
				{
					this._OrderOpenTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exchange", DbType="VarChar(100)")]
		public string Exchange
		{
			get
			{
				return this._Exchange;
			}
			set
			{
				if ((this._Exchange != value))
				{
					this._Exchange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryExchange", DbType="VarChar(100)")]
		public string PrimaryExchange
		{
			get
			{
				return this._PrimaryExchange;
			}
			set
			{
				if ((this._PrimaryExchange != value))
				{
					this._PrimaryExchange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(10)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this._Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Action
		{
			get
			{
				return this._Action;
			}
			set
			{
				if ((this._Action != value))
				{
					this._Action = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalQuantity", DbType="Float NOT NULL")]
		public double TotalQuantity
		{
			get
			{
				return this._TotalQuantity;
			}
			set
			{
				if ((this._TotalQuantity != value))
				{
					this._TotalQuantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderType", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string OrderType
		{
			get
			{
				return this._OrderType;
			}
			set
			{
				if ((this._OrderType != value))
				{
					this._OrderType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitPrice", DbType="Float")]
		public System.Nullable<double> LimitPrice
		{
			get
			{
				return this._LimitPrice;
			}
			set
			{
				if ((this._LimitPrice != value))
				{
					this._LimitPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuxPrice", DbType="Float")]
		public System.Nullable<double> AuxPrice
		{
			get
			{
				return this._AuxPrice;
			}
			set
			{
				if ((this._AuxPrice != value))
				{
					this._AuxPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tif", DbType="VarChar(20)")]
		public string Tif
		{
			get
			{
				return this._Tif;
			}
			set
			{
				if ((this._Tif != value))
				{
					this._Tif = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActiveStartTime
		{
			get
			{
				return this._ActiveStartTime;
			}
			set
			{
				if ((this._ActiveStartTime != value))
				{
					this._ActiveStartTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveStopTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActiveStopTime
		{
			get
			{
				return this._ActiveStopTime;
			}
			set
			{
				if ((this._ActiveStopTime != value))
				{
					this._ActiveStopTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OcaGroup", DbType="VarChar(50)")]
		public string OcaGroup
		{
			get
			{
				return this._OcaGroup;
			}
			set
			{
				if ((this._OcaGroup != value))
				{
					this._OcaGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OcaType", DbType="Int")]
		public System.Nullable<int> OcaType
		{
			get
			{
				return this._OcaType;
			}
			set
			{
				if ((this._OcaType != value))
				{
					this._OcaType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderRef", DbType="VarChar(200)")]
		public string OrderRef
		{
			get
			{
				return this._OrderRef;
			}
			set
			{
				if ((this._OrderRef != value))
				{
					this._OrderRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transmit", DbType="Bit")]
		public System.Nullable<bool> Transmit
		{
			get
			{
				return this._Transmit;
			}
			set
			{
				if ((this._Transmit != value))
				{
					this._Transmit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
		public System.Nullable<int> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlockOrder", DbType="Bit")]
		public System.Nullable<bool> BlockOrder
		{
			get
			{
				return this._BlockOrder;
			}
			set
			{
				if ((this._BlockOrder != value))
				{
					this._BlockOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SweepToFill", DbType="Bit")]
		public System.Nullable<bool> SweepToFill
		{
			get
			{
				return this._SweepToFill;
			}
			set
			{
				if ((this._SweepToFill != value))
				{
					this._SweepToFill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplaySize", DbType="Int")]
		public System.Nullable<int> DisplaySize
		{
			get
			{
				return this._DisplaySize;
			}
			set
			{
				if ((this._DisplaySize != value))
				{
					this._DisplaySize = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TriggerMethod", DbType="Int")]
		public System.Nullable<int> TriggerMethod
		{
			get
			{
				return this._TriggerMethod;
			}
			set
			{
				if ((this._TriggerMethod != value))
				{
					this._TriggerMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutsideRth", DbType="Bit")]
		public System.Nullable<bool> OutsideRth
		{
			get
			{
				return this._OutsideRth;
			}
			set
			{
				if ((this._OutsideRth != value))
				{
					this._OutsideRth = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hidden", DbType="Bit")]
		public System.Nullable<bool> Hidden
		{
			get
			{
				return this._Hidden;
			}
			set
			{
				if ((this._Hidden != value))
				{
					this._Hidden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodAfterTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GoodAfterTime
		{
			get
			{
				return this._GoodAfterTime;
			}
			set
			{
				if ((this._GoodAfterTime != value))
				{
					this._GoodAfterTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodTillDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GoodTillDate
		{
			get
			{
				return this._GoodTillDate;
			}
			set
			{
				if ((this._GoodTillDate != value))
				{
					this._GoodTillDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverridePerentageConstraints", DbType="Bit")]
		public System.Nullable<bool> OverridePerentageConstraints
		{
			get
			{
				return this._OverridePerentageConstraints;
			}
			set
			{
				if ((this._OverridePerentageConstraints != value))
				{
					this._OverridePerentageConstraints = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rule80A", DbType="VarChar(100)")]
		public string Rule80A
		{
			get
			{
				return this._Rule80A;
			}
			set
			{
				if ((this._Rule80A != value))
				{
					this._Rule80A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllOrNone", DbType="Bit")]
		public System.Nullable<bool> AllOrNone
		{
			get
			{
				return this._AllOrNone;
			}
			set
			{
				if ((this._AllOrNone != value))
				{
					this._AllOrNone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinQty", DbType="Int")]
		public System.Nullable<int> MinQty
		{
			get
			{
				return this._MinQty;
			}
			set
			{
				if ((this._MinQty != value))
				{
					this._MinQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitMargin", DbType="VarChar(100)")]
		public string InitMargin
		{
			get
			{
				return this._InitMargin;
			}
			set
			{
				if ((this._InitMargin != value))
				{
					this._InitMargin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaintMargin", DbType="VarChar(100)")]
		public string MaintMargin
		{
			get
			{
				return this._MaintMargin;
			}
			set
			{
				if ((this._MaintMargin != value))
				{
					this._MaintMargin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EquityWithLoan", DbType="VarChar(100)")]
		public string EquityWithLoan
		{
			get
			{
				return this._EquityWithLoan;
			}
			set
			{
				if ((this._EquityWithLoan != value))
				{
					this._EquityWithLoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commission", DbType="Float")]
		public System.Nullable<double> Commission
		{
			get
			{
				return this._Commission;
			}
			set
			{
				if ((this._Commission != value))
				{
					this._Commission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinCommission", DbType="Float")]
		public System.Nullable<double> MinCommission
		{
			get
			{
				return this._MinCommission;
			}
			set
			{
				if ((this._MinCommission != value))
				{
					this._MinCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxCommission", DbType="Float")]
		public System.Nullable<double> MaxCommission
		{
			get
			{
				return this._MaxCommission;
			}
			set
			{
				if ((this._MaxCommission != value))
				{
					this._MaxCommission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommissionCurrency", DbType="VarChar(10)")]
		public string CommissionCurrency
		{
			get
			{
				return this._CommissionCurrency;
			}
			set
			{
				if ((this._CommissionCurrency != value))
				{
					this._CommissionCurrency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WarningTaxt", DbType="VarChar(MAX)")]
		public string WarningTaxt
		{
			get
			{
				return this._WarningTaxt;
			}
			set
			{
				if ((this._WarningTaxt != value))
				{
					this._WarningTaxt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filled", DbType="Float")]
		public System.Nullable<double> Filled
		{
			get
			{
				return this._Filled;
			}
			set
			{
				if ((this._Filled != value))
				{
					this._Filled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remaining", DbType="Float")]
		public System.Nullable<double> Remaining
		{
			get
			{
				return this._Remaining;
			}
			set
			{
				if ((this._Remaining != value))
				{
					this._Remaining = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgFillPrice", DbType="Float")]
		public System.Nullable<double> AvgFillPrice
		{
			get
			{
				return this._AvgFillPrice;
			}
			set
			{
				if ((this._AvgFillPrice != value))
				{
					this._AvgFillPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastFillPrice", DbType="Float")]
		public System.Nullable<double> LastFillPrice
		{
			get
			{
				return this._LastFillPrice;
			}
			set
			{
				if ((this._LastFillPrice != value))
				{
					this._LastFillPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhyHeld", DbType="VarChar(MAX)")]
		public string WhyHeld
		{
			get
			{
				return this._WhyHeld;
			}
			set
			{
				if ((this._WhyHeld != value))
				{
					this._WhyHeld = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr", DbType="VarChar(200)")]
		public string Usr
		{
			get
			{
				return this._Usr;
			}
			set
			{
				if ((this._Usr != value))
				{
					this._Usr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this._TS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Trades")]
	public partial class vw_Trade
	{
		
		private long _TradeID;
		
		private string _UserName;
		
		private string _AccountType;
		
		private string _Account;
		
		private string _Strategy;
		
		private string _Folder;
		
		private System.DateTime _AsOfDate;
		
		private int _OrderId;
		
		private int _ClientId;
		
		private int _PermId;
		
		private string _ExecId;
		
		private long _SID;
		
		private string _SecurityName;
		
		private string _SecurityType;
		
		private System.Nullable<System.DateTime> _TradeTime;
		
		private string _Exchange;
		
		private string _PrimaryExchange;
		
		private string _Currency;
		
		private string _Side;
		
		private double _Quantity;
		
		private System.Nullable<double> _Price;
		
		private System.Nullable<int> _Liquidation;
		
		private System.Nullable<double> _CumQty;
		
		private System.Nullable<double> _AvgPrice;
		
		private string _OrderRef;
		
		private string _EvRule;
		
		private System.Nullable<double> _EvMultiplier;
		
		private string _ModelCode;
		
		private System.Nullable<double> _Commission;
		
		private System.Nullable<double> _RealizedPNL;
		
		private System.Nullable<double> _Yield;
		
		private System.Nullable<int> _YieldRedemptionDate;
		
		private string _Usr;
		
		private System.Nullable<System.DateTime> _TS;
		
		public vw_Trade()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeID", DbType="BigInt NOT NULL")]
		public long TradeID
		{
			get
			{
				return this._TradeID;
			}
			set
			{
				if ((this._TradeID != value))
				{
					this._TradeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="VarChar(200)")]
		public string AccountType
		{
			get
			{
				return this._AccountType;
			}
			set
			{
				if ((this._AccountType != value))
				{
					this._AccountType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strategy", DbType="VarChar(200)")]
		public string Strategy
		{
			get
			{
				return this._Strategy;
			}
			set
			{
				if ((this._Strategy != value))
				{
					this._Strategy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Folder", DbType="VarChar(200)")]
		public string Folder
		{
			get
			{
				return this._Folder;
			}
			set
			{
				if ((this._Folder != value))
				{
					this._Folder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AsOfDate", DbType="Date NOT NULL")]
		public System.DateTime AsOfDate
		{
			get
			{
				return this._AsOfDate;
			}
			set
			{
				if ((this._AsOfDate != value))
				{
					this._AsOfDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderId", DbType="Int NOT NULL")]
		public int OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				if ((this._OrderId != value))
				{
					this._OrderId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientId", DbType="Int NOT NULL")]
		public int ClientId
		{
			get
			{
				return this._ClientId;
			}
			set
			{
				if ((this._ClientId != value))
				{
					this._ClientId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermId", DbType="Int NOT NULL")]
		public int PermId
		{
			get
			{
				return this._PermId;
			}
			set
			{
				if ((this._PermId != value))
				{
					this._PermId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecId", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ExecId
		{
			get
			{
				return this._ExecId;
			}
			set
			{
				if ((this._ExecId != value))
				{
					this._ExecId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SID", DbType="BigInt NOT NULL")]
		public long SID
		{
			get
			{
				return this._SID;
			}
			set
			{
				if ((this._SID != value))
				{
					this._SID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityName", DbType="VarChar(200)")]
		public string SecurityName
		{
			get
			{
				return this._SecurityName;
			}
			set
			{
				if ((this._SecurityName != value))
				{
					this._SecurityName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityType", DbType="VarChar(200)")]
		public string SecurityType
		{
			get
			{
				return this._SecurityType;
			}
			set
			{
				if ((this._SecurityType != value))
				{
					this._SecurityType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TradeTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> TradeTime
		{
			get
			{
				return this._TradeTime;
			}
			set
			{
				if ((this._TradeTime != value))
				{
					this._TradeTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exchange", DbType="VarChar(100)")]
		public string Exchange
		{
			get
			{
				return this._Exchange;
			}
			set
			{
				if ((this._Exchange != value))
				{
					this._Exchange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryExchange", DbType="VarChar(100)")]
		public string PrimaryExchange
		{
			get
			{
				return this._PrimaryExchange;
			}
			set
			{
				if ((this._PrimaryExchange != value))
				{
					this._PrimaryExchange = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Currency", DbType="VarChar(10)")]
		public string Currency
		{
			get
			{
				return this._Currency;
			}
			set
			{
				if ((this._Currency != value))
				{
					this._Currency = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Side", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Side
		{
			get
			{
				return this._Side;
			}
			set
			{
				if ((this._Side != value))
				{
					this._Side = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float NOT NULL")]
		public double Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Float")]
		public System.Nullable<double> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liquidation", DbType="Int")]
		public System.Nullable<int> Liquidation
		{
			get
			{
				return this._Liquidation;
			}
			set
			{
				if ((this._Liquidation != value))
				{
					this._Liquidation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CumQty", DbType="Float")]
		public System.Nullable<double> CumQty
		{
			get
			{
				return this._CumQty;
			}
			set
			{
				if ((this._CumQty != value))
				{
					this._CumQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgPrice", DbType="Float")]
		public System.Nullable<double> AvgPrice
		{
			get
			{
				return this._AvgPrice;
			}
			set
			{
				if ((this._AvgPrice != value))
				{
					this._AvgPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderRef", DbType="VarChar(200)")]
		public string OrderRef
		{
			get
			{
				return this._OrderRef;
			}
			set
			{
				if ((this._OrderRef != value))
				{
					this._OrderRef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvRule", DbType="VarChar(200)")]
		public string EvRule
		{
			get
			{
				return this._EvRule;
			}
			set
			{
				if ((this._EvRule != value))
				{
					this._EvRule = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EvMultiplier", DbType="Float")]
		public System.Nullable<double> EvMultiplier
		{
			get
			{
				return this._EvMultiplier;
			}
			set
			{
				if ((this._EvMultiplier != value))
				{
					this._EvMultiplier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelCode", DbType="VarChar(100)")]
		public string ModelCode
		{
			get
			{
				return this._ModelCode;
			}
			set
			{
				if ((this._ModelCode != value))
				{
					this._ModelCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commission", DbType="Float")]
		public System.Nullable<double> Commission
		{
			get
			{
				return this._Commission;
			}
			set
			{
				if ((this._Commission != value))
				{
					this._Commission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealizedPNL", DbType="Float")]
		public System.Nullable<double> RealizedPNL
		{
			get
			{
				return this._RealizedPNL;
			}
			set
			{
				if ((this._RealizedPNL != value))
				{
					this._RealizedPNL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yield", DbType="Float")]
		public System.Nullable<double> Yield
		{
			get
			{
				return this._Yield;
			}
			set
			{
				if ((this._Yield != value))
				{
					this._Yield = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YieldRedemptionDate", DbType="Int")]
		public System.Nullable<int> YieldRedemptionDate
		{
			get
			{
				return this._YieldRedemptionDate;
			}
			set
			{
				if ((this._YieldRedemptionDate != value))
				{
					this._YieldRedemptionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr", DbType="VarChar(200)")]
		public string Usr
		{
			get
			{
				return this._Usr;
			}
			set
			{
				if ((this._Usr != value))
				{
					this._Usr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> TS
		{
			get
			{
				return this._TS;
			}
			set
			{
				if ((this._TS != value))
				{
					this._TS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
